# Библиотека `pandas`: часть 2

*Алла Тамбовцева*

## Домашнее задание 

### Описание домашнего задания и формат сдачи

В домашнем задании необходимо решить предложенные задачи по программированию – вписать свой код в ячейки после условий задач вместо комментария `### YOUR CODE HERE ###` в файле *homework-pandas2.ipynb* и сохранить изменения, используя опцию *Save and Checkpoint* из вкладки меню *File* или кнопку *Save and Checkpoint* на панели инструментов. Итоговый файл в формате `.ipynb` (файл Jupyter Notebook) необходимо загрузить в личный кабинет обучающей онлайн платформы Skillbox (https://go.skillbox.ru/) и отправить на проверку.

Файл `Fishing.csv` содержит результаты опроса о рыбалке: респонденты, заполняя опросник, подробно описывали свою недавнюю рыбалку.

**Описание переменных в датафрейме:**


* `mode`: выбранный тип рыбалки: на берегу (`beach`), на пирсе (`pier`), в своей лодке (`boat`) и в арендованной лодке (`charter`);

* `price`: стоимость выбранного типа рыбалки;

* `catch`: коэффициент улова при выбранном типе рыбалки;

* `pbeach`: стоимость рыбалки на берегу;

* `ppier`: стоимость рыбалки на пирсе;

* `pboat`: стоимость рыбалки на своей лодке;

* `pcharter`: стоимость рыбалки на арендованной лодке;

* `cbeach`: коэффициент улова на рыбалке на берегу;

* `cpier`: коэффициент улова на рыбалке на пирсе;

* `cboat`: коэффициент улова на рыбалке на своей лодке;

* `ccharter`: коэффициент улова на рыбалке на арендованной лодке;

* `income`: доход в месяц.

Подробнее об опросе и исследовании можно почитать в [статье](https://core.ac.uk/download/pdf/38934845.pdf) J.Herriges, C.Kling *"Nonlinear Income Effects in Random Utility Models"* (1999).

### Задание 1

Загрузить таблицу из файла `Fishing.csv` и сохранить её в датафрейм `dat`. 
Вывести на экран первые 8 строк загруженного датафрейма.

In [1]:
### YOUR CODE HERE ###
import pandas as pd
import numpy as np

dat = pd.read_csv("Fishing.csv")
dat[:8]

,Unnamed: 0,Unnamed: 0.1,mode,price,catch,pbeach,ppier,pboat,pcharter,cbeach,cpier,cboat,ccharter,income
0,0,1,charter,182.930,0.5391,157.930,157.930,157.930,182.930,0.0678,0.0503,0.2601,0.5391,7083.3317
1,1,2,charter,34.534,0.4671,15.114,15.114,10.534,34.534,0.1049,0.0451,0.1574,0.4671,1249.9998
2,2,3,boat,24.334,0.2413,161.874,161.874,24.334,59.334,0.5333,0.4522,0.2413,1.0266,3749.9999
3,3,4,pier,15.134,0.0789,15.134,15.134,55.930,84.930,0.0678,0.0789,0.1643,0.5391,2083.3332
4,4,5,boat,41.514,0.1082,106.930,106.930,41.514,71.014,0.0678,0.0503,0.1082,0.3240,4583.3320
5,5,6,charter,63.934,0.3975,192.474,192.474,28.934,63.934,0.5333,0.4522,0.1665,0.3975,4583.3320
6,6,7,beach,51.934,0.0678,51.934,51.934,191.930,220.930,0.0678,0.0789,0.1643,0.5391,8750.0010
7,7,8,charter,56.714,0.0209,15.134,15.134,21.714,56.714,0.0678,0.0789,0.0102,0.0209,2083.3332

### Задание 2

Добавить, используя метод `.apply()`, столбец `log_income`, содержащий натуральный логарифм доходов респондентов.

In [2]:
### YOUR CODE HERE ###
dat["log_income"] = dat["income"].apply(np.log)
dat.head()

,Unnamed: 0,Unnamed: 0.1,mode,price,catch,pbeach,ppier,pboat,pcharter,cbeach,cpier,cboat,ccharter,income,log_income
0,0,1,charter,182.930,0.5391,157.930,157.930,157.930,182.930,0.0678,0.0503,0.2601,0.5391,7083.3317,8.865500
1,1,2,charter,34.534,0.4671,15.114,15.114,10.534,34.534,0.1049,0.0451,0.1574,0.4671,1249.9998,7.130899
2,2,3,boat,24.334,0.2413,161.874,161.874,24.334,59.334,0.5333,0.4522,0.2413,1.0266,3749.9999,8.229511
3,3,4,pier,15.134,0.0789,15.134,15.134,55.930,84.930,0.0678,0.0789,0.1643,0.5391,2083.3332,7.641724
4,4,5,boat,41.514,0.1082,106.930,106.930,41.514,71.014,0.0678,0.0503,0.1082,0.3240,4583.3320,8.430182

### Задание 3

Посчитать для каждого респондента абсолютное значение отклонения `price` от `pbeach`  и сохранить результат в столбец `pdiff`.

***Подсказка 1:*** для нахождения абсолютного значения числа используется функция `abs()`. Пример:

    abs(-8)
    8

***Подсказка 2:*** пример с lamda-функцией в первом уроке этого модуля.

In [7]:
### YOUR CODE HERE ###
dat["pdiff"] = dat[["price", "pbeach"]].apply(lambda x: abs(x.price - x.pbeach), axis=1)
dat.head()

,Unnamed: 0,Unnamed: 0.1,mode,price,catch,pbeach,ppier,pboat,pcharter,cbeach,cpier,cboat,ccharter,income,log_income,pdiff
0,0,1,charter,182.930,0.5391,157.930,157.930,157.930,182.930,0.0678,0.0503,0.2601,0.5391,7083.3317,8.865500,25.000
1,1,2,charter,34.534,0.4671,15.114,15.114,10.534,34.534,0.1049,0.0451,0.1574,0.4671,1249.9998,7.130899,19.420
2,2,3,boat,24.334,0.2413,161.874,161.874,24.334,59.334,0.5333,0.4522,0.2413,1.0266,3749.9999,8.229511,137.540
3,3,4,pier,15.134,0.0789,15.134,15.134,55.930,84.930,0.0678,0.0789,0.1643,0.5391,2083.3332,7.641724,0.000
4,4,5,boat,41.514,0.1082,106.930,106.930,41.514,71.014,0.0678,0.0503,0.1082,0.3240,4583.3320,8.430182,65.416

### Задание 4

Сгруппировать наблюдения в таблице по признаку тип рыбалки (`mode`) и вывести для каждого типа среднюю цену (`price`), которую респонденты заплатили за рыбалку.

In [8]:
### YOUR CODE HERE ###
dat[["mode", "price"]].groupby("mode").agg("mean")

             price
mode
beach    35.699493
boat     41.606813
charter  75.096942
pier     30.571326

### Задание 5

Сгруппировать наблюдения в таблице по признаку тип рыбалки (`mode`) и вывести для каждого типа разницу между медианным и средним значением цены (`price`), которую респонденты заплатили за рыбалку.

**Посказка:** можно написать свою lambda-функцию для подсчёта разницы между медианой и средним и применить её внутри метода для агрегирования. Внимание: название самостоятельно написанной функции будет уже вводиться без кавычек.

In [19]:
### YOUR CODE HERE ###
df = dat[["mode", "price"]].groupby("mode").agg(["median", "mean", lambda x: np.median(x) - np.mean(x)])
#Нашел также другой способ постобработки
#df["diff"] = df.apply(lambda x: x["price", "median"] - x["price", "mean"], axis=1)
df

          price
         median       mean   <lambda>
mode
beach    19.308  35.699493 -16.391493
boat     24.602  41.606813 -17.004813
charter  56.870  75.096942 -18.226942
pier     16.629  30.571326 -13.942326

### Задание 6

Сгруппировать наблюдения в таблице по признаку тип рыбалки (`mode`) и сохранить полученные датафреймы (один для каждого типа рыбалки) в отдельные csv-файлы. В итоге должно получиться четыре разных csv-файла.

**Подсказка 1:** можно запустить следующий код и посмотреть, что получится:

In [20]:
for name, data in dat.groupby("mode"):
    print(name, data)

beach       Unnamed: 0  Unnamed: 0.1   mode    price   catch   pbeach    ppier  \
6              6             7  beach   51.934  0.0678   51.934   51.934
14            14            15  beach   74.514  0.2537   74.514   74.514
16            16            17  beach   48.114  0.1049   48.114   48.114
25            25            26  beach   67.784  0.5333   67.784   67.784
33            33            34  beach    9.522  0.0678    9.522    9.522
48            48            49  beach   24.334  0.0678   24.334   24.334
49            49            50  beach   11.322  0.0678   11.322   11.322
75            75            76  beach    9.522  0.0678    9.522    9.522
76            76            77  beach   24.696  0.0678   24.696   24.696
81            81            82  beach    7.722  0.0678    7.722    7.722
99            99           100  beach   31.740  0.2537   31.740   31.740
100          100           101  beach   19.740  0.2537   19.740   19.740
113          113           114  beach   42.320  0.2537   42.320   42.320
120          120           121  beach   73.002  0.2537   73.002   73.002
123          123           124  beach   61.740  0.2537   61.740   61.740
163          163           164  beach   42.772  0.0678   42.772   42.772
165          165           166  beach   15.572  0.0678   15.572   15.572
168          168           169  beach  124.350  0.2537  124.350  124.350
173          173           174  beach   22.372  0.0678   22.372   22.372
180          180           181  beach   49.572  0.0678   49.572   49.572
188          188           189  beach   34.914  0.2537   34.914   34.914
201          201           202  beach  117.306  0.0678  117.306  117.306
216          216           217  beach  120.004  0.0678  120.004  120.004
236          236           237  beach   21.386  0.0678   21.386   21.386
237          237           238  beach    9.522  0.0678    9.522    9.522
242          242           243  beach    9.522  0.0678    9.522    9.522
243          243           244  beach   71.442  0.0678   71.442   71.442
261          261           262  beach    4.122  0.0678    4.122    4.122
263          263           264  beach   71.442  0.0678   71.442   71.442
278          278           279  beach   13.290  0.0678   13.290   13.290
...          ...           ...    ...      ...     ...      ...      ...
978          978           979  beach    7.998  0.5333    7.998    7.998
980          980           981  beach   14.476  0.2537   14.476   14.476
997          997           998  beach   17.496  0.5333   17.496   17.496
1004        1004          1005  beach   76.176  0.2537   76.176   76.176
1007        1007          1008  beach    5.496  0.5333    5.496    5.496
1009        1009          1010  beach    7.896  0.5333    7.896    7.896
1011        1011          1012  beach    3.290  0.5333    3.290    3.290
1012        1012          1013  beach    2.290  0.5333    2.290    2.290
1013        1013          1014  beach    1.290  0.5333    1.290    1.290
1022        1022          1023  beach   11.450  0.5333   11.450   11.450
1027        1027          1028  beach   26.450  0.5333   26.450   26.450
1030        1030          1031  beach   21.450  0.5333   21.450   21.450
1035        1035          1036  beach   11.450  0.5333   11.450   11.450
1042        1042          1043  beach   15.870  0.5333   15.870   15.870
1054        1054          1055  beach   12.696  0.5333   12.696   12.696
1073        1073          1074  beach   30.888  0.5333   30.888   30.888
1093        1093          1094  beach   17.496  0.5333   17.496   17.496
1104        1104          1105  beach   94.506  0.2537   94.506   94.506
1114        1114          1115  beach    6.290  0.5333    6.290    6.290
1119        1119          1120  beach    4.290  0.5333    4.290    4.290
1120        1120          1121  beach    4.290  0.5333    4.290    4.290
1122        1122          1123  beach    6.290  0.5333    6.290    6.290
1123        1123          1124  beach    9.290  0.5333    9.290    9.290
1153        1153          1154  beach  105.906  0.2537  105.906  105.906
1159        1159          1160  beach   18.876  0.2537   18.876   18.876
1167        1167          1168  beach   23.688  0.5333   23.688   23.688
1173        1173          1174  beach   62.634  0.0678   62.634   62.634
1176        1176          1177  beach  121.836  0.5333  121.836  121.836
1178        1178          1179  beach  235.436  0.5333  235.436  235.436
1180        1180          1181  beach   36.636  0.5333   36.636   36.636

        pboat  pcharter  cbeach   cpier   cboat  ccharter       income  \
6     191.930   220.930  0.0678  0.0789  0.1643    0.5391   8750.00100
14     74.514    93.014  0.2537  0.1498  0.2339    0.6288   8750.00100
16     33.534    57.534  0.1049  0.0451  0.1574    0.4671   5416.66670
25     17.862    52.862  0.5333  0.4522  0.2413    1.0266   1249.99980
33     78.292   107.292  0.0678  0.0789  0.0014    0.0029   3749.99990
48     89.930   118.930  0.0678  0.0789  0.1643    0.5391   3749.99990
49     93.092   122.092  0.0678  0.0789  0.1643    0.5391   4583.33200
75     78.292   107.292  0.0678  0.0789  0.1643    0.5391   3749.99990
76    111.132   140.132  0.0678  0.0789  0.1643    0.5391   7916.66630
81     63.492    92.492  0.0678  0.0789  0.0014    0.0029   2916.66660
99     38.088    56.588  0.2537  0.1498  0.2339    0.6288   3749.99990
100    23.688    42.188  0.2537  0.1498  0.2339    0.6288   2083.33320
113    42.320    60.820  0.2537  0.1498  0.0233    0.0219   3749.99990
120    73.002    91.502  0.2537  0.1498  0.2339    0.6288   3749.99990
123    74.088    92.588  0.2537  0.1498  0.2339    0.6288   7916.66630
163   104.414   133.414  0.0678  0.0789  0.1643    0.5391   4583.33200
165    38.014    67.014  0.0678  0.0789  0.1643    0.5391   1249.99980
168   124.350   142.850  0.2537  0.1498  0.2339    0.6288   6250.00130
173    54.614    83.614  0.0678  0.0789  0.1643    0.5391   2083.33320
180   121.014   150.014  0.0678  0.0789  0.1643    0.5391   5416.66670
188    34.914    53.414  0.2537  0.1498  0.2339    0.6288   3749.99990
201   181.104   210.104  0.0678  0.0789  0.1643    0.5391   7916.66630
216   252.640   281.640  0.0678  0.0789  0.1643    0.5391  12499.99800
236    21.386    46.386  0.0678  0.0052  0.1491    0.2421   4583.33200
237     9.522    34.522  0.0678  0.0503  0.2601    0.5391   3749.99990
242     9.522    34.522  0.0678  0.0503  0.0276    0.0029   3749.99990
243    13.122    42.122  0.0678  0.0789  0.1643    0.5391   5416.66670
261     4.122    29.122  0.0678  0.0503  0.2601    0.5391   1249.99980
263    13.122    42.122  0.0678  0.0025  0.0499    0.2421   5416.66670
278    13.290    42.290  0.0678  0.0789  0.1643    0.0041  10416.66600
...       ...       ...     ...     ...     ...       ...          ...
978    51.858    86.858  0.5333  0.4522  0.2413    1.0266    416.66668
980    62.510    81.010  0.2537  0.1498  0.0233    0.0219   2083.33320
997   247.860   282.860  0.5333  0.4522  0.2413    1.0266   5416.66670
1004  139.656   158.156  0.2537  0.1498  0.2339    0.6288   3749.99990
1007   77.860   112.860  0.5333  0.4522  0.1665    0.3975   1249.99980
1009  111.860   146.860  0.5333  0.4522  0.2413    1.0266   2083.33320
1011  101.990   136.990  0.5333  0.4522  0.0051    1.0266   2083.33320
1012   70.990   105.990  0.5333  0.4522  0.1665    0.3975   1249.99980
1013   39.990    74.990  0.5333  0.4522  0.2413    1.0266    416.66668
1022   67.326   102.326  0.5333  0.4522  0.2413    1.0266   1249.99980
1027  155.526   190.526  0.5333  0.4522  0.2413    1.0266   3749.99990
1030  126.126   161.126  0.5333  0.4522  0.2413    1.0266   2916.66660
1035   67.326   102.326  0.5333  0.4522  0.2413    1.0266   1249.99980
1042  195.730   230.730  0.5333  0.4522  0.1665    0.3975   3749.99990
1054  179.860   214.860  0.5333  0.4522  0.0156    0.0058   3749.99990
1073  181.896   216.896  0.5333  0.4522  0.0156    0.0058   2916.66660
1093  247.860   282.860  0.5333  0.4522  0.2413    1.0266   5416.66670
1104  193.986   212.486  0.2537  0.1498  0.0008    0.0027   6250.00130
1114  194.990   229.990  0.5333  0.4522  0.2413    1.0266   4583.33200
1119  132.990   167.990  0.5333  0.4522  0.2413    1.0266   2916.66660
1120  132.990   167.990  0.5333  0.4522  0.2413    1.0266   2916.66660
1122  194.990   229.990  0.5333  0.4522  0.1665    0.3975   4583.33200
1123  287.990   322.990  0.5333  0.4522  0.2413    1.0266   7083.33170
1153  217.386   235.886  0.2537  0.1498  0.0233    0.0219   7083.33170
1159   81.510   100.010  0.2537  0.1498  0.2339    0.6288   2916.66660
1167  139.496   174.496  0.5333  0.4522  0.0156    0.0058   2083.33320
1173  123.552   152.552  0.0678  0.0789  0.0014    0.0029   2916.66660
1176  203.346   238.346  0.5333  0.4522  0.2413    1.0266   2916.66660
1178  392.946   427.946  0.5333  0.4522  0.2413    1.0266   6250.00130
1180   61.146    96.146  0.5333  0.4522  0.1665    0.3975    416.66668

      log_income  pdiff
6       9.076809    0.0
14      9.076809    0.0
16      8.597236    0.0
25      7.130899    0.0
33      8.229511    0.0
48      8.229511    0.0
49      8.430182    0.0
75      8.229511    0.0
76      8.976725    0.0
81      7.978197    0.0
99      8.229511    0.0
100     7.641724    0.0
113     8.229511    0.0
120     8.229511    0.0
123     8.976725    0.0
163     8.430182    0.0
165     7.130899    0.0
168     8.740337    0.0
173     7.641724    0.0
180     8.597236    0.0
188     8.229511    0.0
201     8.976725    0.0
216     9.433484    0.0
236     8.430182    0.0
237     8.229511    0.0
242     8.229511    0.0
243     8.597236    0.0
261     7.130899    0.0
263     8.597236    0.0
278     9.251162    0.0
...          ...    ...
978     6.032287    0.0
980     7.641724    0.0
997     8.597236    0.0
1004    8.229511    0.0
1007    7.130899    0.0
1009    7.641724    0.0
1011    7.641724    0.0
1012    7.130899    0.0
1013    6.032287    0.0
1022    7.130899    0.0
1027    8.229511    0.0
1030    7.978197    0.0
1035    7.130899    0.0
1042    8.229511    0.0
1054    8.229511    0.0
1073    7.978197    0.0
1093    8.597236    0.0
1104    8.740337    0.0
1114    8.430182    0.0
1119    7.978197    0.0
1120    7.978197    0.0
1122    8.430182    0.0
1123    8.865500    0.0
1153    8.865500    0.0
1159    7.978197    0.0
1167    7.641724    0.0
1173    7.978197    0.0
1176    7.978197    0.0
1178    8.740337    0.0
1180    6.032287    0.0

[134 rows x 16 columns]
boat       Unnamed: 0  Unnamed: 0.1  mode    price   catch   pbeach    ppier  \
2              2             3  boat   24.334  0.2413  161.874  161.874
4              4             5  boat   41.514  0.1082  106.930  106.930
8              8             9  boat   34.914  0.0233   34.914   34.914
9              9            10  boat   28.314  0.0233   28.314   28.314
11            11            12  boat   16.722  0.2413  312.144  312.144
18            18            19  boat   11.322  0.0361  211.344  211.344
19            19            20  boat   11.322  0.1574   49.062   49.062
22            22            23  boat   15.134  0.1665  100.674  100.674
27            27            28  boat   74.320  0.0897   72.462   72.462
32            32            33  boat    7.722  0.0023   33.462   33.462
37            37            38  boat   80.608  0.0531   25.648   25.648
40            40            41  boat   46.332  0.1643   10.296   10.296
42            42            43  boat   15.096  0.2413  231.472  231.472
52            52            53  boat    9.522  0.2413  177.744  177.744
53            53            54  boat   10.534  0.0361   70.074   70.074
57            57            58  boat    5.922  0.0613   25.662   25.662
58            58            59  boat   13.122  0.0156  244.944  244.944
63            63            64  boat    9.522  0.1574   41.262   41.262
66            66            67  boat    9.522  0.2413  177.744  177.744
68            68            69  boat   13.122  0.2413  244.944  244.944
70            70            71  boat    7.722  0.0023   33.462   33.462
73            73            74  boat   13.122  0.0361  244.944  244.944
74            74            75  boat   14.922  0.0023   64.662   64.662
77            77            78  boat   33.892  0.2601   33.892   33.892
79            79            80  boat    5.922  0.2413  110.544  110.544
82            82            83  boat    9.522  0.1665  177.744  177.744
83            83            84  boat    4.122  0.1574   17.862   17.862
85            85            86  boat   39.474  0.6817    8.514    8.514
87            87            88  boat   34.914  0.0897   24.334   24.334
92            92            93  boat   66.320  0.0102   64.662   64.662
...          ...           ...   ...      ...     ...      ...      ...
1091        1091          1092  boat    5.496  0.6817   32.976   32.976
1094        1094          1095  boat   30.888  0.7369   97.812   97.812
1098        1098          1099  boat    5.922  0.6817   76.986   76.986
1099        1099          1100  boat   15.792  0.0531   63.168   63.168
1100        1100          1101  boat   20.592  0.0531   82.368   82.368
1102        1102          1103  boat    6.290  0.0531   71.706   71.706
1118        1118          1119  boat   15.790  0.7369  180.006  180.006
1121        1121          1122  boat   48.906  0.0732  204.204  204.204
1127        1127          1128  boat    8.290  0.7369   94.506   94.506
1129        1129          1130  boat    3.290  0.0531   37.506   37.506
1132        1132          1133  boat   10.290  0.7369  117.306  117.306
1133        1133          1134  boat    6.290  0.6817   71.706   71.706
1135        1135          1136  boat   37.506  0.0102  101.990  101.990
1138        1138          1139  boat    5.290  0.7369   60.306   60.306
1139        1139          1140  boat    6.290  0.6817   71.706   71.706
1140        1140          1141  boat    6.290  0.6817   71.706   71.706
1141        1141          1142  boat  132.990  0.0156    4.290    4.290
1142        1142          1143  boat  163.990  0.0361    5.290    5.290
1150        1150          1151  boat    6.290  0.6817   71.706   71.706
1151        1151          1152  boat   60.306  0.0102  163.990  163.990
1152        1152          1153  boat    6.290  0.0531   71.706   71.706
1154        1154          1155  boat   39.990  0.1574   30.186   30.186
1158        1158          1159  boat   71.706  0.0559  194.990  194.990
1160        1160          1161  boat   27.676  0.0143  259.148  259.148
1162        1162          1163  boat   45.288  0.0531  143.412  143.412
1164        1164          1165  boat   69.476  0.0102  388.434  388.434
1170        1170          1171  boat  106.434  0.2413  255.150  255.150
1171        1171          1172  boat  155.802  0.0108  164.834  164.834
1174        1174          1175  boat   86.802  0.0102   91.834   91.834
1181        1181          1182  boat  235.436  0.6817  339.890  339.890

        pboat  pcharter  cbeach   cpier   cboat  ccharter       income  \
2      24.334    59.334  0.5333  0.4522  0.2413    1.0266   3749.99990
4      41.514    71.014  0.0678  0.0503  0.1082    0.3240   4583.33200
8      34.914    53.414  0.2537  0.1498  0.0233    0.0219   3749.99990
9      28.314    46.814  0.2537  0.1498  0.0233    0.0219   2916.66660
11     16.722    51.722  0.5333  0.4522  0.2413    1.0266   7083.33170
18     11.322    46.322  0.5333  0.0069  0.0361    0.4216   4583.33200
19     11.322    35.322  0.1049  0.0451  0.1574    0.4671   4583.33200
22     15.134    50.134  0.5333  0.4522  0.1665    0.3975   2083.33320
27     74.320   109.320  0.0678  0.0789  0.0897    1.0905   7083.33170
32      7.722    31.722  0.1049  0.0451  0.0023    0.0046   2916.66660
37     80.608   105.608  0.2537  0.1498  0.0531    0.0052   1249.99980
40     46.332    75.332  0.0678  0.0789  0.1643    0.5391   2916.66660
42     15.096    50.096  0.5333  0.4522  0.2413    1.0266   4583.33200
52      9.522    44.522  0.5333  0.4522  0.2413    1.0266   3749.99990
53     10.534    45.534  0.5333  0.0069  0.0361    0.4216   1249.99980
57      5.922    29.922  0.1049  0.0079  0.0613    0.3087   2083.33320
58     13.122    48.122  0.5333  0.4522  0.0156    0.0058   5416.66670
63      9.522    33.522  0.1049  0.0451  0.1574    0.4671   3749.99990
66      9.522    44.522  0.5333  0.4522  0.2413    1.0266   3749.99990
68     13.122    48.122  0.5333  0.4522  0.2413    1.0266   5416.66670
70      7.722    31.722  0.1049  0.0451  0.0023    0.0046   2916.66660
73     13.122    48.122  0.5333  0.0069  0.0361    0.4216   5416.66670
74     14.922    38.922  0.1049  0.0451  0.0023    0.0046   6250.00130
77     33.892    58.892  0.0678  0.0503  0.2601    0.5391   1249.99980
79      5.922    40.922  0.5333  0.4522  0.2413    1.0266   2083.33320
82      9.522    44.522  0.5333  0.4522  0.1665    0.3975   3749.99990
83      4.122    28.122  0.1049  0.0451  0.1574    0.4671   1249.99980
85     39.474    64.474  0.2537  0.1498  0.6817    2.3014    416.66668
87     34.914    69.914  0.0678  0.0789  0.0897    1.0905   3749.99990
92     66.320   101.320  0.0678  0.0789  0.0102    0.0209   6250.00130
...       ...       ...     ...     ...     ...       ...          ...
1091    5.496    30.496  0.2537  0.1498  0.6817    2.3014   1249.99980
1094   30.888    55.888  0.2537  0.1498  0.7369    2.3101   2916.66660
1098    5.922    30.922  0.2537  0.1498  0.6817    2.3014   2083.33320
1099   15.792    40.792  0.2537  0.1498  0.0531    0.0052   2083.33320
1100   20.592    45.592  0.2537  0.1498  0.0531    0.0052   2916.66660
1102    6.290    31.290  0.2537  0.1498  0.0531    0.0052   4583.33200
1118   15.790    40.790  0.2537  0.1498  0.7369    2.3101  12499.99800
1121   48.906    78.406  0.0678  0.0052  0.0732    0.1726   2916.66660
1127    8.290    33.290  0.2537  0.1498  0.7369    2.3101   6250.00130
1129    3.290    28.290  0.2537  0.1498  0.0531    0.0052   2083.33320
1132   10.290    35.290  0.2537  0.1498  0.7369    2.3101   7916.66630
1133    6.290    31.290  0.2537  0.1498  0.6817    2.3014   4583.33200
1135   37.506    72.506  0.0678  0.0789  0.0102    0.0209   2083.33320
1138    5.290    30.290  0.2537  0.1498  0.7369    2.3101   3749.99990
1139    6.290    31.290  0.2537  0.1498  0.6817    2.3014   4583.33200
1140    6.290    31.290  0.2537  0.1498  0.6817    2.3014   4583.33200
1141  132.990   167.990  0.5333  0.4522  0.0156    0.0058   2916.66660
1142  163.990   198.990  0.5333  0.0069  0.0361    0.4216   3749.99990
1150    6.290    31.290  0.2537  0.1498  0.6817    2.3014   4583.33200
1151   60.306    95.306  0.0678  0.0789  0.0102    0.0209   3749.99990
1152    6.290    31.290  0.2537  0.1498  0.0531    0.0052   4583.33200
1154   39.990    63.990  0.1049  0.0451  0.1574    0.4671    416.66668
1158   71.706   106.706  0.0678  0.0789  0.0559    0.6456   4583.33200
1160   27.676    57.176  0.0678  0.0503  0.0143    0.0289   4583.33200
1162   45.288    70.288  0.2537  0.1498  0.0531    0.0052   4583.33200
1164   69.476   104.476  0.0678  0.0789  0.0102    0.0209  12499.99800
1170  106.434   141.434  0.5333  0.4522  0.2413    1.0266   5416.66670
1171  155.802   190.802  0.0678  0.0025  0.0108    0.2377   8750.00100
1174   86.802   121.802  0.0678  0.0789  0.0102    0.0209   4583.33200
1181  235.436   260.436  0.2537  0.1498  0.6817    2.3014   6250.00130

      log_income    pdiff
2       8.229511  137.540
4       8.430182   65.416
8       8.229511    0.000
9       7.978197    0.000
11      8.865500  295.422
18      8.430182  200.022
19      8.430182   37.740
22      7.641724   85.540
27      8.865500    1.858
32      7.978197   25.740
37      7.130899   54.960
40      7.978197   36.036
42      8.430182  216.376
52      8.229511  168.222
53      7.130899   59.540
57      7.641724   19.740
58      8.597236  231.822
63      8.229511   31.740
66      8.229511  168.222
68      8.597236  231.822
70      7.978197   25.740
73      8.597236  231.822
74      8.740337   49.740
77      7.130899    0.000

**Подсказка 2:** для сохранения датафрейма в файл используется метод `.to_csv()`. Например, такой код сохранит датафрейм `dat` в файл `"Fish.csv"`:

In [0]:
dat.to_csv("Fish.csv")

**Подсказка 3:** для склеивания строк можно использовать оператор `+`, например:

In [0]:
"my_file" + ".xlsx"

'my_file.xlsx'

In [23]:
### YOUR CODE HERE ###
g = dat.groupby("mode")
for name, data in g:
    data.to_csv("%s.csv" % name)

### Задание 7

Отсортировать строки в датафрейме в соответствии со значениями `income` в порядке убывания таким образом, чтобы результаты сортировки сохранились в исходном датафрейме.

In [24]:
### YOUR CODE HERE ###
dat.sort_values("income", ascending=False, inplace=True)
dat.head()

,Unnamed: 0,Unnamed: 0.1,mode,price,catch,pbeach,ppier,pboat,pcharter,cbeach,cpier,cboat,ccharter,income,log_income,pdiff
524,524,525,charter,240.586,0.5391,167.374,167.374,211.586,240.586,0.0678,0.0789,0.1643,0.5391,12499.998,9.433484,73.212
130,130,131,boat,94.740,0.0108,205.270,205.270,94.740,129.740,0.0678,0.0025,0.0108,0.2377,12499.998,9.433484,110.530
932,932,933,boat,37.896,0.0531,227.376,227.376,37.896,62.896,0.2537,0.1498,0.0531,0.0052,12499.998,9.433484,189.480
36,36,37,pier,120.004,0.0789,120.004,120.004,252.640,281.640,0.0678,0.0789,0.0014,0.0029,12499.998,9.433484,0.000
377,377,378,boat,328.432,0.0023,511.596,511.596,328.432,352.432,0.1049,0.0451,0.0023,0.0046,12499.998,9.433484,183.164

### Задание 8

Отсортировать строки в датафрейме в соответствии со значениями `price` и `income` в порядке возрастания. Можно ли сказать, что люди с более низким доходом и выбравшие более дешёвый тип рыбалки, в целом, предпочитают один тип рыбалки, а люди с более высоким доходом и более дорогой рыбалкой – другой? Ответ записать в виде текстовой ячейки или в виде комментария.

In [28]:
### YOUR CODE HERE ###
dat.sort_values(["price", "income"], inplace=True)
dat[:30]
#Я не вижу явной зависимости

,Unnamed: 0,Unnamed: 0.1,mode,price,catch,pbeach,ppier,pboat,pcharter,cbeach,cpier,cboat,ccharter,income,log_income,pdiff
1105,1105,1106,pier,1.290,0.4522,1.290,1.290,39.990,74.990,0.5333,0.4522,0.0051,1.0266,416.66668,6.032287,0.000
1157,1157,1158,pier,1.290,0.4522,1.290,1.290,39.990,74.990,0.5333,0.4522,0.1665,0.3975,416.66668,6.032287,0.000
1013,1013,1014,beach,1.290,0.5333,1.290,1.290,39.990,74.990,0.5333,0.4522,0.2413,1.0266,416.66668,6.032287,0.000
275,275,276,pier,2.290,0.0789,2.290,2.290,2.290,31.290,0.0678,0.0789,0.0971,0.1648,1249.99980,7.130899,0.000
1155,1155,1156,pier,2.290,0.4522,2.290,2.290,70.990,105.990,0.5333,0.4522,0.2413,1.0266,1249.99980,7.130899,0.000
287,287,288,pier,2.290,0.0789,2.290,2.290,2.290,31.290,0.0678,0.0789,0.1643,0.5391,1249.99980,7.130899,0.000
1116,1116,1117,pier,2.290,0.4522,2.290,2.290,70.990,105.990,0.5333,0.4522,0.2413,1.0266,1249.99980,7.130899,0.000
322,322,323,pier,2.290,0.0503,2.290,2.290,2.290,27.290,0.0678,0.0503,0.2601,0.5391,1249.99980,7.130899,0.000
1012,1012,1013,beach,2.290,0.5333,2.290,2.290,70.990,105.990,0.5333,0.4522,0.1665,0.3975,1249.99980,7.130899,0.000
323,323,324,pier,2.290,0.0503,2.290,2.290,2.290,27.290,0.0678,0.0503,0.2601,0.5391,1249.99980,7.130899,0.000
336,336,337,beach,2.290,0.0678,2.290,2.290,2.290,27.290,0.0678,0.0503,0.0276,0.0029,1249.99980,7.130899,0.000
339,339,340,boat,2.290,0.0276,2.290,2.290,2.290,27.290,0.0678,0.0503,0.0276,0.0029,1249.99980,7.130899,0.000
981,981,982,pier,2.322,0.4522,2.322,2.322,55.470,90.470,0.5333,0.4522,0.2413,1.0266,416.66668,6.032287,0.000
985,985,986,pier,3.096,0.4522,3.096,3.096,43.860,78.860,0.5333,0.4522,0.2413,1.0266,416.66668,6.032287,0.000
1002,1002,1003,boat,3.096,0.0531,18.576,18.576,3.096,28.096,0.2537,0.1498,0.0531,0.0052,416.66668,6.032287,15.480
338,338,339,boat,3.290,0.0276,3.290,3.290,3.290,28.290,0.0678,0.0503,0.0276,0.0029,2083.33320,7.641724,0.000
1010,1010,1011,boat,3.290,0.6817,37.506,37.506,3.290,28.290,0.2537,0.1498,0.6817,2.3014,2083.33320,7.641724,34.216
1011,1011,1012,beach,3.290,0.5333,3.290,3.290,101.990,136.990,0.5333,0.4522,0.0051,1.0266,2083.33320,7.641724,0.000
302,302,303,pier,3.290,0.0503,3.290,3.290,3.290,28.290,0.0678,0.0503,0.0276,0.0029,2083.33320,7.641724,0.000
291,291,292,boat,3.290,0.1574,75.012,75.012,3.290,27.290,0.1049,0.0451,0.1574,0.4671,2083.33320,7.641724,71.722
1129,1129,1130,boat,3.290,0.0531,37.506,37.506,3.290,28.290,0.2537,0.1498,0.0531,0.0052,2083.33320,7.641724,34.216
1130,1130,1131,pier,3.290,0.4522,3.290,3.290,101.990,136.990,0.5333,0.4522,0.2413,1.0266,2083.33320,7.641724,0.000
273,273,274,boat,3.290,0.0014,3.290,3.290,3.290,32.290,0.0678,0.0789,0.0014,0.0029,2083.33320,7.641724,0.000
271,271,272,boat,3.290,0.1665,164.500,164.500,3.290,38.290,0.5333,0.4522,0.1665,0.3975,2083.33320,7.641724,161.210
1110,1110,1111,pier,3.290,0.4522,3.290,3.290,101.990,136.990,0.5333,0.4522,0.2413,1.0266,2083.33320,7.641724,0.000
328,328,329,boat,3.290,0.0230,3.290,3.290,3.290,28.290,0.0678,0.0503,0.0230,0.1648,2083.33320,7.641724,0.000
319,319,320,pier,3.290,0.0052,3.290,3.290,3.290,28.290,0.0678,0.0052,0.1491,0.2421,2083.33320,7.641724,0.000
850,850,851,boat,3.870,0.0559,23.994,23.994,3.870,38.870,0.0678,0.0789,0.0559,0.6456,416.66668,6.032287,20.124
825,825,826,pier,3.870,0.1498,3.870,3.870,16.770,35.270,0.2537,0.1498,0.0233,0.0219,416.66668,6.032287,0.000
878,878,879,boat,3.870,0.7369,22.446,22.446,3.870,28.870,0.2537,0.1498,0.7369,2.3101,416.66668,6.032287,18.576

### Задание 9

Любым известным способом проверить, есть ли в датафрейме пропущенные значения. Если есть, удалить строки с пропущенными значениями. Если нет, написать комментарий, что таких нет.

In [30]:
### YOUR CODE HERE ###
print(len(dat))
dat.dropna(inplace=True)
print(len(dat))

#Выходит, что пустых значений нет

1182
1182

.<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> 
# Дополнительное (необязательное) задание.
<br>

### Задание 1

Загрузить датафрейм из файла `wgi_fh.csv`, учитывая, что в качестве разделителя столбцов используется точка с запятой, а в качестве десятичного разделителя – запятая (опции `sep=` и `decimal=` в функции `read_csv()` соответственно).

Файл содержит данные за 2016 по различным политологическим индексам. Датафрейм содержит следующие столбцы:

* `country`: страна;
* `cnt_code`: код страны (аббревиатура);
* `year`: год;
* `va`: индекс подотчётности *Voice & Accountability (WGI)*;
* `ps`: индекс политической стабильности *Political Stability and Lack of Violence (WGI)*;
* `ge`: индекс эффективности правительства *Government Effectiveness (WGI)*;
* `rq`: индекс качества управления *Regulatory Quality (WGI)*;
* `rl`: индекс верховенства закона *Rule of Law (WGI)*;
* `cc`: индекс контроля коррупции *Control of Corruption (WGI)*;
* `fh`: индекс свободы *Freedom House (Freedom Rating)*.

Подробнее про индексы можно почитать на этой [странице](https://www.hse.ru/org/hse/4432173/mathbase/databases/db_18).

In [0]:
### YOUR CODE HERE ###

### Задание 2

Вывести общую информацию по датафрейму: число строк и столбцов, типы данных в таблице. Есть ли в таблице пропущенные значения? Привести код и дать ответ в виде комментария.

In [0]:
### YOUR CODE HERE ###

### Задание 3

Если в датафрейме есть строки с пропущенными значениями, удалить их. Сохранить изменения в исходном датафрейме.

In [0]:
### YOUR CODE HERE ###

### Задание 4

Назвать строки в датафрейме в соответствии со столбцом `cnt_code`. Удалить данный столбец из датафрейма.

In [0]:
### YOUR CODE HERE ###

### Задание 5

Отсортировать строки в таблице в соответствии со значениями столбцов с индексами *Control of Corruption*  и *Voice & Accountability* таким образом, чтобы результаты сортировки были сохранены сразу в исходном датафрейме.

In [0]:
### YOUR CODE HERE ###

### Задание 6

Используя метод `.apply()`, создать столбец `cc_round` со значениями индекса *Control of Corruption*, округлёнными до первого знака после запятой.

In [0]:
### YOUR CODE HERE ###

### Задание 7

Добавить в датафрейм столбец `fh_status`, в котором будут храниться типы стран в зависимости от значения индекса *Freedom House* (значения типов стран: `"free"`, `"partly free"`, `"not free"`). Соответствие значений `fh` типам стран см. в Table 3 в конце [этой](https://freedomhouse.org/sites/default/files/2020-02/Methodology_FIW_2016.pdf) страницы.

**Подсказка:** здесь понадобится функция, которая возвращает разные значения в зависимости от выполнения условий. Её можно написать через `def` или `lambda`. Больше про функции можно почитать на [pythontutor.ru](https://pythontutor.ru/lessons/functions/).

In [0]:
### YOUR CODE HERE ###

### Задание 8

Сгруппировать строки в датафрейме в соответствии со значениями столбца `fh_status`, полученного в предыдущем задании и вывести минимальное, среднее и максимальное значение показателя *Political Stability and Lack of Violence* по каждой группе.

In [0]:
### YOUR CODE HERE ###

### Задание 9

Сгруппировать строки в датафрейме в соответствии со значениями столбца `fh_status` и записать строки, относящиеся к разным группам, в отдельные csv-файлы.

**Подсказка 1:** цикл `for`.

**Подсказка 2:**  [метод](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html) `.to_csv()` для выгрузки датафреймов `pandas` в csv-файлы.

In [0]:
### YOUR CODE HERE ###

### Задание 10

Создайте (любым способом) маленький датафрейм, состоящий из двух столбцов:

* `fh_type`: тип страны;
* `count`: число стран данного типа.

    Постройте, используя полученный датафрейм, столбиковую диаграмму (*barplot*), опираясь на [эту](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.plot.bar.html) документацию. Чтобы увидеть график явно, прямо в текущем ноутбуке, допишите в начале ячейки с кодом для графика следующую строку:
    
        %matplotlib inline

**Подсказка:** число наблюдений — это функция `count`, её можно использовать наравне с `min`, `mean` и прочими.

In [0]:
### YOUR CODE HERE ###